window.esdocSearchIndex = [
  [
    "spray-wrtc/lib/exceptions/exemptyview.js~exemptyview",
    "class/lib/exceptions/exemptyview.js~ExEmptyView.html",
    "<span>ExEmptyView</span> <span class=\"search-result-import-path\">spray-wrtc/lib/exceptions/exemptyview.js</span>",
    "class"
  ],
  [
    "spray-wrtc/lib/exceptions/exmessage.js~exmessage",
    "class/lib/exceptions/exmessage.js~ExMessage.html",
    "<span>ExMessage</span> <span class=\"search-result-import-path\">spray-wrtc/lib/exceptions/exmessage.js</span>",
    "class"
  ],
  [
    "spray-wrtc/lib/exceptions/expeernotfound.js~expeernotfound",
    "class/lib/exceptions/expeernotfound.js~ExPeerNotFound.html",
    "<span>ExPeerNotFound</span> <span class=\"search-result-import-path\">spray-wrtc/lib/exceptions/expeernotfound.js</span>",
    "class"
  ],
  [
    "spray-wrtc/lib/messages/mexchange.js~mexchange",
    "class/lib/messages/mexchange.js~MExchange.html",
    "<span>MExchange</span> <span class=\"search-result-import-path\">spray-wrtc/lib/messages/mexchange.js</span>",
    "class"
  ],
  [
    "spray-wrtc/lib/messages/mjoin.js~mjoin",
    "class/lib/messages/mjoin.js~MJoin.html",
    "<span>MJoin</span> <span class=\"search-result-import-path\">spray-wrtc/lib/messages/mjoin.js</span>",
    "class"
  ],
  [
    "spray-wrtc~n2n",
    "variable/index.html#static-variable-N2N",
    "<span>N2N</span> <span class=\"search-result-import-path\">spray-wrtc</span>",
    "variable"
  ],
  [
    "spray-wrtc/lib/partialview.js~partialview",
    "class/lib/partialview.js~PartialView.html",
    "<span>PartialView</span> <span class=\"search-result-import-path\">spray-wrtc/lib/partialview.js</span>",
    "class"
  ],
  [
    "spray-wrtc~spray",
    "class/lib/spray.js~Spray.html",
    "<span>Spray</span> <span class=\"search-result-import-path\">spray-wrtc</span>",
    "class"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array",
    "BuiltinExternal/ECMAScriptExternal.js~Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~arraybuffer",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer",
    "BuiltinExternal/ECMAScriptExternal.js~ArrayBuffer",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "BuiltinExternal/ECMAScriptExternal.js~Boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~dataview",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView",
    "BuiltinExternal/ECMAScriptExternal.js~DataView",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~date",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date",
    "BuiltinExternal/ECMAScriptExternal.js~Date",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~error",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error",
    "BuiltinExternal/ECMAScriptExternal.js~Error",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~evalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/EvalError",
    "BuiltinExternal/ECMAScriptExternal.js~EvalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float32Array",
    "BuiltinExternal/ECMAScriptExternal.js~Float32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float64array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float64Array",
    "BuiltinExternal/ECMAScriptExternal.js~Float64Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "BuiltinExternal/ECMAScriptExternal.js~Function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generator",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator",
    "BuiltinExternal/ECMAScriptExternal.js~Generator",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generatorfunction",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/GeneratorFunction",
    "BuiltinExternal/ECMAScriptExternal.js~GeneratorFunction",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~infinity",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Infinity",
    "BuiltinExternal/ECMAScriptExternal.js~Infinity",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int16Array",
    "BuiltinExternal/ECMAScriptExternal.js~Int16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int32Array",
    "BuiltinExternal/ECMAScriptExternal.js~Int32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int8Array",
    "BuiltinExternal/ECMAScriptExternal.js~Int8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~internalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/InternalError",
    "BuiltinExternal/ECMAScriptExternal.js~InternalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~json",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON",
    "BuiltinExternal/ECMAScriptExternal.js~JSON",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~map",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map",
    "BuiltinExternal/ECMAScriptExternal.js~Map",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~nan",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NaN",
    "BuiltinExternal/ECMAScriptExternal.js~NaN",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "BuiltinExternal/ECMAScriptExternal.js~Number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "BuiltinExternal/ECMAScriptExternal.js~Object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~promise",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise",
    "BuiltinExternal/ECMAScriptExternal.js~Promise",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~proxy",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy",
    "BuiltinExternal/ECMAScriptExternal.js~Proxy",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~rangeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RangeError",
    "BuiltinExternal/ECMAScriptExternal.js~RangeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~referenceerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ReferenceError",
    "BuiltinExternal/ECMAScriptExternal.js~ReferenceError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~reflect",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect",
    "BuiltinExternal/ECMAScriptExternal.js~Reflect",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~regexp",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp",
    "BuiltinExternal/ECMAScriptExternal.js~RegExp",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~set",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set",
    "BuiltinExternal/ECMAScriptExternal.js~Set",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "BuiltinExternal/ECMAScriptExternal.js~String",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~symbol",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol",
    "BuiltinExternal/ECMAScriptExternal.js~Symbol",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~syntaxerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SyntaxError",
    "BuiltinExternal/ECMAScriptExternal.js~SyntaxError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~typeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypeError",
    "BuiltinExternal/ECMAScriptExternal.js~TypeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~urierror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/URIError",
    "BuiltinExternal/ECMAScriptExternal.js~URIError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint16Array",
    "BuiltinExternal/ECMAScriptExternal.js~Uint16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint32Array",
    "BuiltinExternal/ECMAScriptExternal.js~Uint32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8clampedarray",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8ClampedArray",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8ClampedArray",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakmap",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap",
    "BuiltinExternal/ECMAScriptExternal.js~WeakMap",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakset",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakSet",
    "BuiltinExternal/ECMAScriptExternal.js~WeakSet",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "BuiltinExternal/ECMAScriptExternal.js~boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "BuiltinExternal/ECMAScriptExternal.js~function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~null",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/null",
    "BuiltinExternal/ECMAScriptExternal.js~null",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "BuiltinExternal/ECMAScriptExternal.js~number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "BuiltinExternal/ECMAScriptExternal.js~object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "BuiltinExternal/ECMAScriptExternal.js~string",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~undefined",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/undefined",
    "BuiltinExternal/ECMAScriptExternal.js~undefined",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~audiocontext",
    "https://developer.mozilla.org/en/docs/Web/API/AudioContext",
    "BuiltinExternal/WebAPIExternal.js~AudioContext",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~canvasrenderingcontext2d",
    "https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D",
    "BuiltinExternal/WebAPIExternal.js~CanvasRenderingContext2D",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~documentfragment",
    "https://developer.mozilla.org/en-US/docs/Web/API/DocumentFragment",
    "BuiltinExternal/WebAPIExternal.js~DocumentFragment",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~element",
    "https://developer.mozilla.org/en-US/docs/Web/API/Element",
    "BuiltinExternal/WebAPIExternal.js~Element",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~event",
    "https://developer.mozilla.org/en-US/docs/Web/API/Event",
    "BuiltinExternal/WebAPIExternal.js~Event",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~node",
    "https://developer.mozilla.org/en-US/docs/Web/API/Node",
    "BuiltinExternal/WebAPIExternal.js~Node",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~nodelist",
    "https://developer.mozilla.org/en-US/docs/Web/API/NodeList",
    "BuiltinExternal/WebAPIExternal.js~NodeList",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~xmlhttprequest",
    "https://developer.mozilla.org/en/docs/Web/API/XMLHttpRequest",
    "BuiltinExternal/WebAPIExternal.js~XMLHttpRequest",
    "external"
  ],
  [
    "lib/exceptions/exemptyview.js",
    "file/lib/exceptions/exemptyview.js.html",
    "lib/exceptions/exemptyview.js",
    "file"
  ],
  [
    "lib/exceptions/exemptyview.js~exemptyview#constructor",
    "class/lib/exceptions/exemptyview.js~ExEmptyView.html#instance-constructor-constructor",
    "lib/exceptions/exemptyview.js~ExEmptyView#constructor",
    "method"
  ],
  [
    "lib/exceptions/exemptyview.js~exemptyview#message",
    "class/lib/exceptions/exemptyview.js~ExEmptyView.html#instance-member-message",
    "lib/exceptions/exemptyview.js~ExEmptyView#message",
    "member"
  ],
  [
    "lib/exceptions/exemptyview.js~exemptyview#source",
    "class/lib/exceptions/exemptyview.js~ExEmptyView.html#instance-member-source",
    "lib/exceptions/exemptyview.js~ExEmptyView#source",
    "member"
  ],
  [
    "lib/exceptions/exmessage.js",
    "file/lib/exceptions/exmessage.js.html",
    "lib/exceptions/exmessage.js",
    "file"
  ],
  [
    "lib/exceptions/exmessage.js~exmessage#constructor",
    "class/lib/exceptions/exmessage.js~ExMessage.html#instance-constructor-constructor",
    "lib/exceptions/exmessage.js~ExMessage#constructor",
    "method"
  ],
  [
    "lib/exceptions/exmessage.js~exmessage#message",
    "class/lib/exceptions/exmessage.js~ExMessage.html#instance-member-message",
    "lib/exceptions/exmessage.js~ExMessage#message",
    "member"
  ],
  [
    "lib/exceptions/exmessage.js~exmessage#reason",
    "class/lib/exceptions/exmessage.js~ExMessage.html#instance-member-reason",
    "lib/exceptions/exmessage.js~ExMessage#reason",
    "member"
  ],
  [
    "lib/exceptions/exmessage.js~exmessage#source",
    "class/lib/exceptions/exmessage.js~ExMessage.html#instance-member-source",
    "lib/exceptions/exmessage.js~ExMessage#source",
    "member"
  ],
  [
    "lib/exceptions/expeernotfound.js",
    "file/lib/exceptions/expeernotfound.js.html",
    "lib/exceptions/expeernotfound.js",
    "file"
  ],
  [
    "lib/exceptions/expeernotfound.js~expeernotfound#constructor",
    "class/lib/exceptions/expeernotfound.js~ExPeerNotFound.html#instance-constructor-constructor",
    "lib/exceptions/expeernotfound.js~ExPeerNotFound#constructor",
    "method"
  ],
  [
    "lib/exceptions/expeernotfound.js~expeernotfound#peer",
    "class/lib/exceptions/expeernotfound.js~ExPeerNotFound.html#instance-member-peer",
    "lib/exceptions/expeernotfound.js~ExPeerNotFound#peer",
    "member"
  ],
  [
    "lib/exceptions/expeernotfound.js~expeernotfound#source",
    "class/lib/exceptions/expeernotfound.js~ExPeerNotFound.html#instance-member-source",
    "lib/exceptions/expeernotfound.js~ExPeerNotFound#source",
    "member"
  ],
  [
    "lib/messages/mexchange.js",
    "file/lib/messages/mexchange.js.html",
    "lib/messages/mexchange.js",
    "file"
  ],
  [
    "lib/messages/mexchange.js~mexchange#constructor",
    "class/lib/messages/mexchange.js~MExchange.html#instance-constructor-constructor",
    "lib/messages/mexchange.js~MExchange#constructor",
    "method"
  ],
  [
    "lib/messages/mexchange.js~mexchange#inview",
    "class/lib/messages/mexchange.js~MExchange.html#instance-member-inview",
    "lib/messages/mexchange.js~MExchange#inview",
    "member"
  ],
  [
    "lib/messages/mexchange.js~mexchange#type",
    "class/lib/messages/mexchange.js~MExchange.html#instance-member-type",
    "lib/messages/mexchange.js~MExchange#type",
    "member"
  ],
  [
    "lib/messages/mjoin.js",
    "file/lib/messages/mjoin.js.html",
    "lib/messages/mjoin.js",
    "file"
  ],
  [
    "lib/messages/mjoin.js~mjoin#constructor",
    "class/lib/messages/mjoin.js~MJoin.html#instance-constructor-constructor",
    "lib/messages/mjoin.js~MJoin#constructor",
    "method"
  ],
  [
    "lib/messages/mjoin.js~mjoin#type",
    "class/lib/messages/mjoin.js~MJoin.html#instance-member-type",
    "lib/messages/mjoin.js~MJoin#type",
    "member"
  ],
  [
    "lib/partialview.js",
    "file/lib/partialview.js.html",
    "lib/partialview.js",
    "file"
  ],
  [
    "lib/partialview.js~partialview#add",
    "class/lib/partialview.js~PartialView.html#instance-method-add",
    "lib/partialview.js~PartialView#add",
    "method"
  ],
  [
    "lib/partialview.js~partialview#constructor",
    "class/lib/partialview.js~PartialView.html#instance-constructor-constructor",
    "lib/partialview.js~PartialView#constructor",
    "method"
  ],
  [
    "lib/partialview.js~partialview#increment",
    "class/lib/partialview.js~PartialView.html#instance-method-increment",
    "lib/partialview.js~PartialView#increment",
    "method"
  ],
  [
    "lib/partialview.js~partialview#leastfrequent",
    "class/lib/partialview.js~PartialView.html#instance-get-leastFrequent",
    "lib/partialview.js~PartialView#leastFrequent",
    "member"
  ],
  [
    "lib/partialview.js~partialview#oldest",
    "class/lib/partialview.js~PartialView.html#instance-get-oldest",
    "lib/partialview.js~PartialView#oldest",
    "member"
  ],
  [
    "lib/partialview.js~partialview#removeall",
    "class/lib/partialview.js~PartialView.html#instance-method-removeAll",
    "lib/partialview.js~PartialView#removeAll",
    "method"
  ],
  [
    "lib/partialview.js~partialview#removeoldest",
    "class/lib/partialview.js~PartialView.html#instance-method-removeOldest",
    "lib/partialview.js~PartialView#removeOldest",
    "method"
  ],
  [
    "lib/partialview.js~partialview#removeyoungest",
    "class/lib/partialview.js~PartialView.html#instance-method-removeYoungest",
    "lib/partialview.js~PartialView#removeYoungest",
    "method"
  ],
  [
    "lib/spray.js",
    "file/lib/spray.js.html",
    "lib/spray.js",
    "file"
  ],
  [
    "lib/spray.js~spray#_close",
    "class/lib/spray.js~Spray.html#instance-method-_close",
    "lib/spray.js~Spray#_close",
    "method"
  ],
  [
    "lib/spray.js~spray#_exchange",
    "class/lib/spray.js~Spray.html#instance-method-_exchange",
    "lib/spray.js~Spray#_exchange",
    "method"
  ],
  [
    "lib/spray.js~spray#_getsample",
    "class/lib/spray.js~Spray.html#instance-method-_getSample",
    "lib/spray.js~Spray#_getSample",
    "method"
  ],
  [
    "lib/spray.js~spray#_onarcdown",
    "class/lib/spray.js~Spray.html#instance-method-_onArcDown",
    "lib/spray.js~Spray#_onArcDown",
    "method"
  ],
  [
    "lib/spray.js~spray#_onexchange",
    "class/lib/spray.js~Spray.html#instance-method-_onExchange",
    "lib/spray.js~Spray#_onExchange",
    "method"
  ],
  [
    "lib/spray.js~spray#_onjoin",
    "class/lib/spray.js~Spray.html#instance-method-_onJoin",
    "lib/spray.js~Spray#_onJoin",
    "method"
  ],
  [
    "lib/spray.js~spray#_onpeerdown",
    "class/lib/spray.js~Spray.html#instance-method-_onPeerDown",
    "lib/spray.js~Spray#_onPeerDown",
    "method"
  ],
  [
    "lib/spray.js~spray#_open",
    "class/lib/spray.js~Spray.html#instance-method-_open",
    "lib/spray.js~Spray#_open",
    "method"
  ],
  [
    "lib/spray.js~spray#_receive",
    "class/lib/spray.js~Spray.html#instance-method-_receive",
    "lib/spray.js~Spray#_receive",
    "method"
  ],
  [
    "lib/spray.js~spray#_start",
    "class/lib/spray.js~Spray.html#instance-method-_start",
    "lib/spray.js~Spray#_start",
    "method"
  ],
  [
    "lib/spray.js~spray#_stop",
    "class/lib/spray.js~Spray.html#instance-method-_stop",
    "lib/spray.js~Spray#_stop",
    "method"
  ],
  [
    "lib/spray.js~spray#_updatestate",
    "class/lib/spray.js~Spray.html#instance-method-_updateState",
    "lib/spray.js~Spray#_updateState",
    "method"
  ],
  [
    "lib/spray.js~spray#constructor",
    "class/lib/spray.js~Spray.html#instance-constructor-constructor",
    "lib/spray.js~Spray#constructor",
    "method"
  ],
  [
    "lib/spray.js~spray#getpeers",
    "class/lib/spray.js~Spray.html#instance-method-getPeers",
    "lib/spray.js~Spray#getPeers",
    "method"
  ],
  [
    "lib/spray.js~spray#join",
    "class/lib/spray.js~Spray.html#instance-method-join",
    "lib/spray.js~Spray#join",
    "method"
  ],
  [
    "lib/spray.js~spray#partialview",
    "class/lib/spray.js~Spray.html#instance-member-partialView",
    "lib/spray.js~Spray#partialView",
    "member"
  ],
  [
    "lib/spray.js~spray#periodic",
    "class/lib/spray.js~Spray.html#instance-member-periodic",
    "lib/spray.js~Spray#periodic",
    "member"
  ],
  [
    "lib/spray.js~spray#state",
    "class/lib/spray.js~Spray.html#instance-member-state",
    "lib/spray.js~Spray#state",
    "member"
  ]
]