window.esdocSearchIndex = [
  [
    "spray-wrtc/lib/exceptions/exemptyview.js~exemptyview",
    "class/lib/exceptions/exemptyview.js~ExEmptyView.html",
    "<span>ExEmptyView</span> <span class=\"search-result-import-path\">spray-wrtc/lib/exceptions/exemptyview.js</span>",
    "class"
  ],
  [
    "spray-wrtc/lib/exceptions/exjoin.js~exjoin",
    "class/lib/exceptions/exjoin.js~ExJoin.html",
    "<span>ExJoin</span> <span class=\"search-result-import-path\">spray-wrtc/lib/exceptions/exjoin.js</span>",
    "class"
  ],
  [
    "spray-wrtc/lib/exceptions/exmessage.js~exmessage",
    "class/lib/exceptions/exmessage.js~ExMessage.html",
    "<span>ExMessage</span> <span class=\"search-result-import-path\">spray-wrtc/lib/exceptions/exmessage.js</span>",
    "class"
  ],
  [
    "spray-wrtc/lib/exceptions/expeernotfound.js~expeernotfound",
    "class/lib/exceptions/expeernotfound.js~ExPeerNotFound.html",
    "<span>ExPeerNotFound</span> <span class=\"search-result-import-path\">spray-wrtc/lib/exceptions/expeernotfound.js</span>",
    "class"
  ],
  [
    "spray-wrtc/lib/messages/mexchange.js~mexchange",
    "class/lib/messages/mexchange.js~MExchange.html",
    "<span>MExchange</span> <span class=\"search-result-import-path\">spray-wrtc/lib/messages/mexchange.js</span>",
    "class"
  ],
  [
    "spray-wrtc/lib/messages/mjoin.js~mjoin",
    "class/lib/messages/mjoin.js~MJoin.html",
    "<span>MJoin</span> <span class=\"search-result-import-path\">spray-wrtc/lib/messages/mjoin.js</span>",
    "class"
  ],
  [
    "spray-wrtc/lib/messages/mleave.js~mleave",
    "class/lib/messages/mleave.js~MLeave.html",
    "<span>MLeave</span> <span class=\"search-result-import-path\">spray-wrtc/lib/messages/mleave.js</span>",
    "class"
  ],
  [
    "spray-wrtc/lib/partialview.js~partialview",
    "class/lib/partialview.js~PartialView.html",
    "<span>PartialView</span> <span class=\"search-result-import-path\">spray-wrtc/lib/partialview.js</span>",
    "class"
  ],
  [
    "spray-wrtc~spray",
    "class/lib/spray.js~Spray.html",
    "<span>Spray</span> <span class=\"search-result-import-path\">spray-wrtc</span>",
    "class"
  ],
  [
    "lib/.external-ecmascript.js~array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array",
    "lib/.external-ecmascript.js~Array",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~arraybuffer",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer",
    "lib/.external-ecmascript.js~ArrayBuffer",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "lib/.external-ecmascript.js~Boolean",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~dataview",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView",
    "lib/.external-ecmascript.js~DataView",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~date",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date",
    "lib/.external-ecmascript.js~Date",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~error",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error",
    "lib/.external-ecmascript.js~Error",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~evalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/EvalError",
    "lib/.external-ecmascript.js~EvalError",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~float32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float32Array",
    "lib/.external-ecmascript.js~Float32Array",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~float64array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float64Array",
    "lib/.external-ecmascript.js~Float64Array",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "lib/.external-ecmascript.js~Function",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~generator",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator",
    "lib/.external-ecmascript.js~Generator",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~generatorfunction",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/GeneratorFunction",
    "lib/.external-ecmascript.js~GeneratorFunction",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~infinity",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Infinity",
    "lib/.external-ecmascript.js~Infinity",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~int16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int16Array",
    "lib/.external-ecmascript.js~Int16Array",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~int32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int32Array",
    "lib/.external-ecmascript.js~Int32Array",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~int8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int8Array",
    "lib/.external-ecmascript.js~Int8Array",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~internalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/InternalError",
    "lib/.external-ecmascript.js~InternalError",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~json",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON",
    "lib/.external-ecmascript.js~JSON",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~map",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map",
    "lib/.external-ecmascript.js~Map",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~nan",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NaN",
    "lib/.external-ecmascript.js~NaN",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "lib/.external-ecmascript.js~Number",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "lib/.external-ecmascript.js~Object",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~promise",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise",
    "lib/.external-ecmascript.js~Promise",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~proxy",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy",
    "lib/.external-ecmascript.js~Proxy",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~rangeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RangeError",
    "lib/.external-ecmascript.js~RangeError",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~referenceerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ReferenceError",
    "lib/.external-ecmascript.js~ReferenceError",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~reflect",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect",
    "lib/.external-ecmascript.js~Reflect",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~regexp",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp",
    "lib/.external-ecmascript.js~RegExp",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~set",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set",
    "lib/.external-ecmascript.js~Set",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "lib/.external-ecmascript.js~String",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~symbol",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol",
    "lib/.external-ecmascript.js~Symbol",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~syntaxerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SyntaxError",
    "lib/.external-ecmascript.js~SyntaxError",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~typeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypeError",
    "lib/.external-ecmascript.js~TypeError",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~urierror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/URIError",
    "lib/.external-ecmascript.js~URIError",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~uint16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint16Array",
    "lib/.external-ecmascript.js~Uint16Array",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~uint32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint32Array",
    "lib/.external-ecmascript.js~Uint32Array",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~uint8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array",
    "lib/.external-ecmascript.js~Uint8Array",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~uint8clampedarray",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8ClampedArray",
    "lib/.external-ecmascript.js~Uint8ClampedArray",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~weakmap",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap",
    "lib/.external-ecmascript.js~WeakMap",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~weakset",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakSet",
    "lib/.external-ecmascript.js~WeakSet",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "lib/.external-ecmascript.js~boolean",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "lib/.external-ecmascript.js~function",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~null",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/null",
    "lib/.external-ecmascript.js~null",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "lib/.external-ecmascript.js~number",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "lib/.external-ecmascript.js~object",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "lib/.external-ecmascript.js~string",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~undefined",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/undefined",
    "lib/.external-ecmascript.js~undefined",
    "external"
  ],
  [
    "lib/exceptions/exemptyview.js",
    "file/lib/exceptions/exemptyview.js.html",
    "lib/exceptions/exemptyview.js",
    "file"
  ],
  [
    "lib/exceptions/exemptyview.js~exemptyview#constructor",
    "class/lib/exceptions/exemptyview.js~ExEmptyView.html#instance-constructor-constructor",
    "lib/exceptions/exemptyview.js~ExEmptyView#constructor",
    "method"
  ],
  [
    "lib/exceptions/exemptyview.js~exemptyview#message",
    "class/lib/exceptions/exemptyview.js~ExEmptyView.html#instance-member-message",
    "lib/exceptions/exemptyview.js~ExEmptyView#message",
    "member"
  ],
  [
    "lib/exceptions/exemptyview.js~exemptyview#source",
    "class/lib/exceptions/exemptyview.js~ExEmptyView.html#instance-member-source",
    "lib/exceptions/exemptyview.js~ExEmptyView#source",
    "member"
  ],
  [
    "lib/exceptions/exjoin.js",
    "file/lib/exceptions/exjoin.js.html",
    "lib/exceptions/exjoin.js",
    "file"
  ],
  [
    "lib/exceptions/exjoin.js~exjoin#constructor",
    "class/lib/exceptions/exjoin.js~ExJoin.html#instance-constructor-constructor",
    "lib/exceptions/exjoin.js~ExJoin#constructor",
    "method"
  ],
  [
    "lib/exceptions/exjoin.js~exjoin#message",
    "class/lib/exceptions/exjoin.js~ExJoin.html#instance-member-message",
    "lib/exceptions/exjoin.js~ExJoin#message",
    "member"
  ],
  [
    "lib/exceptions/exjoin.js~exjoin#source",
    "class/lib/exceptions/exjoin.js~ExJoin.html#instance-member-source",
    "lib/exceptions/exjoin.js~ExJoin#source",
    "member"
  ],
  [
    "lib/exceptions/exmessage.js",
    "file/lib/exceptions/exmessage.js.html",
    "lib/exceptions/exmessage.js",
    "file"
  ],
  [
    "lib/exceptions/exmessage.js~exmessage#constructor",
    "class/lib/exceptions/exmessage.js~ExMessage.html#instance-constructor-constructor",
    "lib/exceptions/exmessage.js~ExMessage#constructor",
    "method"
  ],
  [
    "lib/exceptions/exmessage.js~exmessage#message",
    "class/lib/exceptions/exmessage.js~ExMessage.html#instance-member-message",
    "lib/exceptions/exmessage.js~ExMessage#message",
    "member"
  ],
  [
    "lib/exceptions/exmessage.js~exmessage#reason",
    "class/lib/exceptions/exmessage.js~ExMessage.html#instance-member-reason",
    "lib/exceptions/exmessage.js~ExMessage#reason",
    "member"
  ],
  [
    "lib/exceptions/exmessage.js~exmessage#source",
    "class/lib/exceptions/exmessage.js~ExMessage.html#instance-member-source",
    "lib/exceptions/exmessage.js~ExMessage#source",
    "member"
  ],
  [
    "lib/exceptions/expeernotfound.js",
    "file/lib/exceptions/expeernotfound.js.html",
    "lib/exceptions/expeernotfound.js",
    "file"
  ],
  [
    "lib/exceptions/expeernotfound.js~expeernotfound#constructor",
    "class/lib/exceptions/expeernotfound.js~ExPeerNotFound.html#instance-constructor-constructor",
    "lib/exceptions/expeernotfound.js~ExPeerNotFound#constructor",
    "method"
  ],
  [
    "lib/exceptions/expeernotfound.js~expeernotfound#peer",
    "class/lib/exceptions/expeernotfound.js~ExPeerNotFound.html#instance-member-peer",
    "lib/exceptions/expeernotfound.js~ExPeerNotFound#peer",
    "member"
  ],
  [
    "lib/exceptions/expeernotfound.js~expeernotfound#source",
    "class/lib/exceptions/expeernotfound.js~ExPeerNotFound.html#instance-member-source",
    "lib/exceptions/expeernotfound.js~ExPeerNotFound#source",
    "member"
  ],
  [
    "lib/messages/mexchange.js",
    "file/lib/messages/mexchange.js.html",
    "lib/messages/mexchange.js",
    "file"
  ],
  [
    "lib/messages/mexchange.js~mexchange#constructor",
    "class/lib/messages/mexchange.js~MExchange.html#instance-constructor-constructor",
    "lib/messages/mexchange.js~MExchange#constructor",
    "method"
  ],
  [
    "lib/messages/mexchange.js~mexchange#inview",
    "class/lib/messages/mexchange.js~MExchange.html#instance-member-inview",
    "lib/messages/mexchange.js~MExchange#inview",
    "member"
  ],
  [
    "lib/messages/mexchange.js~mexchange#type",
    "class/lib/messages/mexchange.js~MExchange.html#instance-member-type",
    "lib/messages/mexchange.js~MExchange#type",
    "member"
  ],
  [
    "lib/messages/mjoin.js",
    "file/lib/messages/mjoin.js.html",
    "lib/messages/mjoin.js",
    "file"
  ],
  [
    "lib/messages/mjoin.js~mjoin#constructor",
    "class/lib/messages/mjoin.js~MJoin.html#instance-constructor-constructor",
    "lib/messages/mjoin.js~MJoin#constructor",
    "method"
  ],
  [
    "lib/messages/mjoin.js~mjoin#type",
    "class/lib/messages/mjoin.js~MJoin.html#instance-member-type",
    "lib/messages/mjoin.js~MJoin#type",
    "member"
  ],
  [
    "lib/messages/mleave.js",
    "file/lib/messages/mleave.js.html",
    "lib/messages/mleave.js",
    "file"
  ],
  [
    "lib/messages/mleave.js~mleave#constructor",
    "class/lib/messages/mleave.js~MLeave.html#instance-constructor-constructor",
    "lib/messages/mleave.js~MLeave#constructor",
    "method"
  ],
  [
    "lib/messages/mleave.js~mleave#type",
    "class/lib/messages/mleave.js~MLeave.html#instance-member-type",
    "lib/messages/mleave.js~MLeave#type",
    "member"
  ],
  [
    "lib/partialview.js",
    "file/lib/partialview.js.html",
    "lib/partialview.js",
    "file"
  ],
  [
    "lib/partialview.js~partialview#add",
    "class/lib/partialview.js~PartialView.html#instance-method-add",
    "lib/partialview.js~PartialView#add",
    "method"
  ],
  [
    "lib/partialview.js~partialview#constructor",
    "class/lib/partialview.js~PartialView.html#instance-constructor-constructor",
    "lib/partialview.js~PartialView#constructor",
    "method"
  ],
  [
    "lib/partialview.js~partialview#increment",
    "class/lib/partialview.js~PartialView.html#instance-method-increment",
    "lib/partialview.js~PartialView#increment",
    "method"
  ],
  [
    "lib/partialview.js~partialview#leastfrequent",
    "class/lib/partialview.js~PartialView.html#instance-get-leastFrequent",
    "lib/partialview.js~PartialView#leastFrequent",
    "member"
  ],
  [
    "lib/partialview.js~partialview#oldest",
    "class/lib/partialview.js~PartialView.html#instance-get-oldest",
    "lib/partialview.js~PartialView#oldest",
    "member"
  ],
  [
    "lib/partialview.js~partialview#removeall",
    "class/lib/partialview.js~PartialView.html#instance-method-removeAll",
    "lib/partialview.js~PartialView#removeAll",
    "method"
  ],
  [
    "lib/partialview.js~partialview#removeoldest",
    "class/lib/partialview.js~PartialView.html#instance-method-removeOldest",
    "lib/partialview.js~PartialView#removeOldest",
    "method"
  ],
  [
    "lib/partialview.js~partialview#removeyoungest",
    "class/lib/partialview.js~PartialView.html#instance-method-removeYoungest",
    "lib/partialview.js~PartialView#removeYoungest",
    "method"
  ],
  [
    "lib/spray.js",
    "file/lib/spray.js.html",
    "lib/spray.js",
    "file"
  ],
  [
    "lib/spray.js~spray#_checkpartialview",
    "class/lib/spray.js~Spray.html#instance-method-_checkPartialView",
    "lib/spray.js~Spray#_checkPartialView",
    "method"
  ],
  [
    "lib/spray.js~spray#_close",
    "class/lib/spray.js~Spray.html#instance-method-_close",
    "lib/spray.js~Spray#_close",
    "method"
  ],
  [
    "lib/spray.js~spray#_exchange",
    "class/lib/spray.js~Spray.html#instance-method-_exchange",
    "lib/spray.js~Spray#_exchange",
    "method"
  ],
  [
    "lib/spray.js~spray#_getsample",
    "class/lib/spray.js~Spray.html#instance-method-_getSample",
    "lib/spray.js~Spray#_getSample",
    "method"
  ],
  [
    "lib/spray.js~spray#_inject",
    "class/lib/spray.js~Spray.html#instance-method-_inject",
    "lib/spray.js~Spray#_inject",
    "method"
  ],
  [
    "lib/spray.js~spray#_onarcdown",
    "class/lib/spray.js~Spray.html#instance-method-_onArcDown",
    "lib/spray.js~Spray#_onArcDown",
    "method"
  ],
  [
    "lib/spray.js~spray#_onexchange",
    "class/lib/spray.js~Spray.html#instance-method-_onExchange",
    "lib/spray.js~Spray#_onExchange",
    "method"
  ],
  [
    "lib/spray.js~spray#_onjoin",
    "class/lib/spray.js~Spray.html#instance-method-_onJoin",
    "lib/spray.js~Spray#_onJoin",
    "method"
  ],
  [
    "lib/spray.js~spray#_onleave",
    "class/lib/spray.js~Spray.html#instance-method-_onLeave",
    "lib/spray.js~Spray#_onLeave",
    "method"
  ],
  [
    "lib/spray.js~spray#_onpeerdown",
    "class/lib/spray.js~Spray.html#instance-method-_onPeerDown",
    "lib/spray.js~Spray#_onPeerDown",
    "method"
  ],
  [
    "lib/spray.js~spray#_open",
    "class/lib/spray.js~Spray.html#instance-method-_open",
    "lib/spray.js~Spray#_open",
    "method"
  ],
  [
    "lib/spray.js~spray#_receive",
    "class/lib/spray.js~Spray.html#instance-method-_receive",
    "lib/spray.js~Spray#_receive",
    "method"
  ],
  [
    "lib/spray.js~spray#_start",
    "class/lib/spray.js~Spray.html#instance-method-_start",
    "lib/spray.js~Spray#_start",
    "method"
  ],
  [
    "lib/spray.js~spray#_stop",
    "class/lib/spray.js~Spray.html#instance-method-_stop",
    "lib/spray.js~Spray#_stop",
    "method"
  ],
  [
    "lib/spray.js~spray#_updatestate",
    "class/lib/spray.js~Spray.html#instance-method-_updateState",
    "lib/spray.js~Spray#_updateState",
    "method"
  ],
  [
    "lib/spray.js~spray#constructor",
    "class/lib/spray.js~Spray.html#instance-constructor-constructor",
    "lib/spray.js~Spray#constructor",
    "method"
  ],
  [
    "lib/spray.js~spray#getpeers",
    "class/lib/spray.js~Spray.html#instance-method-getPeers",
    "lib/spray.js~Spray#getPeers",
    "method"
  ],
  [
    "lib/spray.js~spray#join",
    "class/lib/spray.js~Spray.html#instance-method-join",
    "lib/spray.js~Spray#join",
    "method"
  ],
  [
    "lib/spray.js~spray#leave",
    "class/lib/spray.js~Spray.html#instance-method-leave",
    "lib/spray.js~Spray#leave",
    "method"
  ],
  [
    "lib/spray.js~spray#partialview",
    "class/lib/spray.js~Spray.html#instance-member-partialView",
    "lib/spray.js~Spray#partialView",
    "member"
  ],
  [
    "lib/spray.js~spray#periodic",
    "class/lib/spray.js~Spray.html#instance-member-periodic",
    "lib/spray.js~Spray#periodic",
    "member"
  ],
  [
    "lib/spray.js~spray#state",
    "class/lib/spray.js~Spray.html#instance-member-state",
    "lib/spray.js~Spray#state",
    "member"
  ]
]