window.esdocSearchIndex = [
  [
    "spray-wrtc~eventemitter",
    "variable/index.html#static-variable-EventEmitter",
    "<span>EventEmitter</span> <span class=\"search-result-import-path\">spray-wrtc</span>",
    "variable"
  ],
  [
    "spray-wrtc/lib/messages.js~mexchange",
    "function/index.html#static-function-MExchange",
    "<span>MExchange</span> <span class=\"search-result-import-path\">spray-wrtc/lib/messages.js</span>",
    "function"
  ],
  [
    "spray-wrtc/lib/partialview.js~partialview",
    "class/lib/partialview.js~PartialView.html",
    "<span>PartialView</span> <span class=\"search-result-import-path\">spray-wrtc/lib/partialview.js</span>",
    "class"
  ],
  [
    "spray-wrtc/lib/extended-sorted-array.js~sortedarray",
    "variable/index.html#static-variable-SortedArray",
    "<span>SortedArray</span> <span class=\"search-result-import-path\">spray-wrtc/lib/extended-sorted-array.js</span>",
    "variable"
  ],
  [
    "spray-wrtc~spray",
    "class/lib/spray.js~Spray.html",
    "<span>Spray</span> <span class=\"search-result-import-path\">spray-wrtc</span>",
    "class"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array",
    "BuiltinExternal/ECMAScriptExternal.js~Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~arraybuffer",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer",
    "BuiltinExternal/ECMAScriptExternal.js~ArrayBuffer",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "BuiltinExternal/ECMAScriptExternal.js~Boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~dataview",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView",
    "BuiltinExternal/ECMAScriptExternal.js~DataView",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~date",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date",
    "BuiltinExternal/ECMAScriptExternal.js~Date",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~error",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error",
    "BuiltinExternal/ECMAScriptExternal.js~Error",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~evalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/EvalError",
    "BuiltinExternal/ECMAScriptExternal.js~EvalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float32Array",
    "BuiltinExternal/ECMAScriptExternal.js~Float32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float64array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float64Array",
    "BuiltinExternal/ECMAScriptExternal.js~Float64Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "BuiltinExternal/ECMAScriptExternal.js~Function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generator",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator",
    "BuiltinExternal/ECMAScriptExternal.js~Generator",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generatorfunction",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/GeneratorFunction",
    "BuiltinExternal/ECMAScriptExternal.js~GeneratorFunction",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~infinity",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Infinity",
    "BuiltinExternal/ECMAScriptExternal.js~Infinity",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int16Array",
    "BuiltinExternal/ECMAScriptExternal.js~Int16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int32Array",
    "BuiltinExternal/ECMAScriptExternal.js~Int32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int8Array",
    "BuiltinExternal/ECMAScriptExternal.js~Int8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~internalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/InternalError",
    "BuiltinExternal/ECMAScriptExternal.js~InternalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~json",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON",
    "BuiltinExternal/ECMAScriptExternal.js~JSON",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~map",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map",
    "BuiltinExternal/ECMAScriptExternal.js~Map",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~nan",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NaN",
    "BuiltinExternal/ECMAScriptExternal.js~NaN",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "BuiltinExternal/ECMAScriptExternal.js~Number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "BuiltinExternal/ECMAScriptExternal.js~Object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~promise",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise",
    "BuiltinExternal/ECMAScriptExternal.js~Promise",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~proxy",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy",
    "BuiltinExternal/ECMAScriptExternal.js~Proxy",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~rangeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RangeError",
    "BuiltinExternal/ECMAScriptExternal.js~RangeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~referenceerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ReferenceError",
    "BuiltinExternal/ECMAScriptExternal.js~ReferenceError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~reflect",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect",
    "BuiltinExternal/ECMAScriptExternal.js~Reflect",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~regexp",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp",
    "BuiltinExternal/ECMAScriptExternal.js~RegExp",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~set",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set",
    "BuiltinExternal/ECMAScriptExternal.js~Set",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "BuiltinExternal/ECMAScriptExternal.js~String",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~symbol",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol",
    "BuiltinExternal/ECMAScriptExternal.js~Symbol",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~syntaxerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SyntaxError",
    "BuiltinExternal/ECMAScriptExternal.js~SyntaxError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~typeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypeError",
    "BuiltinExternal/ECMAScriptExternal.js~TypeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~urierror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/URIError",
    "BuiltinExternal/ECMAScriptExternal.js~URIError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint16Array",
    "BuiltinExternal/ECMAScriptExternal.js~Uint16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint32Array",
    "BuiltinExternal/ECMAScriptExternal.js~Uint32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8clampedarray",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8ClampedArray",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8ClampedArray",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakmap",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap",
    "BuiltinExternal/ECMAScriptExternal.js~WeakMap",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakset",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakSet",
    "BuiltinExternal/ECMAScriptExternal.js~WeakSet",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "BuiltinExternal/ECMAScriptExternal.js~boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "BuiltinExternal/ECMAScriptExternal.js~function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~null",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/null",
    "BuiltinExternal/ECMAScriptExternal.js~null",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "BuiltinExternal/ECMAScriptExternal.js~number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "BuiltinExternal/ECMAScriptExternal.js~object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "BuiltinExternal/ECMAScriptExternal.js~string",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~undefined",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/undefined",
    "BuiltinExternal/ECMAScriptExternal.js~undefined",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~audiocontext",
    "https://developer.mozilla.org/en/docs/Web/API/AudioContext",
    "BuiltinExternal/WebAPIExternal.js~AudioContext",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~canvasrenderingcontext2d",
    "https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D",
    "BuiltinExternal/WebAPIExternal.js~CanvasRenderingContext2D",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~documentfragment",
    "https://developer.mozilla.org/en-US/docs/Web/API/DocumentFragment",
    "BuiltinExternal/WebAPIExternal.js~DocumentFragment",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~element",
    "https://developer.mozilla.org/en-US/docs/Web/API/Element",
    "BuiltinExternal/WebAPIExternal.js~Element",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~event",
    "https://developer.mozilla.org/en-US/docs/Web/API/Event",
    "BuiltinExternal/WebAPIExternal.js~Event",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~node",
    "https://developer.mozilla.org/en-US/docs/Web/API/Node",
    "BuiltinExternal/WebAPIExternal.js~Node",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~nodelist",
    "https://developer.mozilla.org/en-US/docs/Web/API/NodeList",
    "BuiltinExternal/WebAPIExternal.js~NodeList",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~xmlhttprequest",
    "https://developer.mozilla.org/en/docs/Web/API/XMLHttpRequest",
    "BuiltinExternal/WebAPIExternal.js~XMLHttpRequest",
    "external"
  ],
  [
    "lib/extended-sorted-array.js",
    "file/lib/extended-sorted-array.js.html",
    "lib/extended-sorted-array.js",
    "file"
  ],
  [
    "lib/messages.js",
    "file/lib/messages.js.html",
    "lib/messages.js",
    "file"
  ],
  [
    "lib/partialview.js",
    "file/lib/partialview.js.html",
    "lib/partialview.js",
    "file"
  ],
  [
    "lib/partialview.js~partialview#addneighbor",
    "class/lib/partialview.js~PartialView.html#instance-method-addNeighbor",
    "lib/partialview.js~PartialView#addNeighbor",
    "method"
  ],
  [
    "lib/partialview.js~partialview#array",
    "class/lib/partialview.js~PartialView.html#instance-member-array",
    "lib/partialview.js~PartialView#array",
    "member"
  ],
  [
    "lib/partialview.js~partialview#clear",
    "class/lib/partialview.js~PartialView.html#instance-method-clear",
    "lib/partialview.js~PartialView#clear",
    "method"
  ],
  [
    "lib/partialview.js~partialview#comparator",
    "class/lib/partialview.js~PartialView.html#instance-member-comparator",
    "lib/partialview.js~PartialView#comparator",
    "member"
  ],
  [
    "lib/partialview.js~partialview#constructor",
    "class/lib/partialview.js~PartialView.html#instance-constructor-constructor",
    "lib/partialview.js~PartialView#constructor",
    "method"
  ],
  [
    "lib/partialview.js~partialview#contains",
    "class/lib/partialview.js~PartialView.html#instance-method-contains",
    "lib/partialview.js~PartialView#contains",
    "method"
  ],
  [
    "lib/partialview.js~partialview#get",
    "class/lib/partialview.js~PartialView.html#instance-method-get",
    "lib/partialview.js~PartialView#get",
    "method"
  ],
  [
    "lib/partialview.js~partialview#getindex",
    "class/lib/partialview.js~PartialView.html#instance-method-getIndex",
    "lib/partialview.js~PartialView#getIndex",
    "method"
  ],
  [
    "lib/partialview.js~partialview#getoldest",
    "class/lib/partialview.js~PartialView.html#instance-method-getOldest",
    "lib/partialview.js~PartialView#getOldest",
    "method"
  ],
  [
    "lib/partialview.js~partialview#getsample",
    "class/lib/partialview.js~PartialView.html#instance-method-getSample",
    "lib/partialview.js~PartialView#getSample",
    "method"
  ],
  [
    "lib/partialview.js~partialview#increment",
    "class/lib/partialview.js~PartialView.html#instance-method-increment",
    "lib/partialview.js~PartialView#increment",
    "method"
  ],
  [
    "lib/partialview.js~partialview#length",
    "class/lib/partialview.js~PartialView.html#instance-method-length",
    "lib/partialview.js~PartialView#length",
    "method"
  ],
  [
    "lib/partialview.js~partialview#removeall",
    "class/lib/partialview.js~PartialView.html#instance-method-removeAll",
    "lib/partialview.js~PartialView#removeAll",
    "method"
  ],
  [
    "lib/partialview.js~partialview#removepeer",
    "class/lib/partialview.js~PartialView.html#instance-method-removePeer",
    "lib/partialview.js~PartialView#removePeer",
    "method"
  ],
  [
    "lib/partialview.js~partialview#removepeerage",
    "class/lib/partialview.js~PartialView.html#instance-method-removePeerAge",
    "lib/partialview.js~PartialView#removePeerAge",
    "method"
  ],
  [
    "lib/partialview.js~partialview#removesample",
    "class/lib/partialview.js~PartialView.html#instance-method-removeSample",
    "lib/partialview.js~PartialView#removeSample",
    "method"
  ],
  [
    "lib/partialview.js~partialview#replace",
    "class/lib/partialview.js~PartialView.html#instance-method-replace",
    "lib/partialview.js~PartialView#replace",
    "method"
  ],
  [
    "lib/partialview.js~partialview#usedcoef",
    "class/lib/partialview.js~PartialView.html#instance-member-usedCoef",
    "lib/partialview.js~PartialView#usedCoef",
    "member"
  ],
  [
    "lib/spray.js",
    "file/lib/spray.js.html",
    "lib/spray.js",
    "file"
  ],
  [
    "lib/spray.js~spray#deltatime",
    "class/lib/spray.js~Spray.html#instance-member-DELTATIME",
    "lib/spray.js~Spray#DELTATIME",
    "member"
  ],
  [
    "lib/spray.js~spray#retry",
    "class/lib/spray.js~Spray.html#instance-member-RETRY",
    "lib/spray.js~Spray#RETRY",
    "member"
  ],
  [
    "lib/spray.js~spray#connection",
    "class/lib/spray.js~Spray.html#instance-method-connection",
    "lib/spray.js~Spray#connection",
    "method"
  ],
  [
    "lib/spray.js~spray#constructor",
    "class/lib/spray.js~Spray.html#instance-constructor-constructor",
    "lib/spray.js~Spray#constructor",
    "method"
  ],
  [
    "lib/spray.js~spray#exchange",
    "class/lib/spray.js~Spray.html#instance-method-exchange",
    "lib/spray.js~Spray#exchange",
    "method"
  ],
  [
    "lib/spray.js~spray#getpeers",
    "class/lib/spray.js~Spray.html#instance-method-getPeers",
    "lib/spray.js~Spray#getPeers",
    "method"
  ],
  [
    "lib/spray.js~spray#leave",
    "class/lib/spray.js~Spray.html#instance-method-leave",
    "lib/spray.js~Spray#leave",
    "method"
  ],
  [
    "lib/spray.js~spray#log",
    "class/lib/spray.js~Spray.html#instance-method-log",
    "lib/spray.js~Spray#log",
    "method"
  ],
  [
    "lib/spray.js~spray#neighborhoods",
    "class/lib/spray.js~Spray.html#instance-member-neighborhoods",
    "lib/spray.js~Spray#neighborhoods",
    "member"
  ],
  [
    "lib/spray.js~spray#onarcdown",
    "class/lib/spray.js~Spray.html#instance-method-onArcDown",
    "lib/spray.js~Spray#onArcDown",
    "method"
  ],
  [
    "lib/spray.js~spray#onexchange",
    "class/lib/spray.js~Spray.html#instance-method-onExchange",
    "lib/spray.js~Spray#onExchange",
    "method"
  ],
  [
    "lib/spray.js~spray#onpeerdown",
    "class/lib/spray.js~Spray.html#instance-method-onPeerDown",
    "lib/spray.js~Spray#onPeerDown",
    "method"
  ],
  [
    "lib/spray.js~spray#opts",
    "class/lib/spray.js~Spray.html#instance-member-opts",
    "lib/spray.js~Spray#opts",
    "member"
  ],
  [
    "lib/spray.js~spray#partialview",
    "class/lib/spray.js~Spray.html#instance-member-partialView",
    "lib/spray.js~Spray#partialView",
    "member"
  ],
  [
    "lib/spray.js~spray#profile",
    "class/lib/spray.js~Spray.html#instance-member-profile",
    "lib/spray.js~Spray#profile",
    "member"
  ],
  [
    "lib/spray.js~spray#protocol",
    "class/lib/spray.js~Spray.html#instance-member-protocol",
    "lib/spray.js~Spray#protocol",
    "member"
  ],
  [
    "lib/spray.js~spray#send",
    "class/lib/spray.js~Spray.html#instance-method-send",
    "lib/spray.js~Spray#send",
    "method"
  ],
  [
    "lib/spray.js~spray#state",
    "class/lib/spray.js~Spray.html#instance-member-state",
    "lib/spray.js~Spray#state",
    "member"
  ],
  [
    "lib/spray.js~spray#tostring",
    "class/lib/spray.js~Spray.html#instance-method-toString",
    "lib/spray.js~Spray#toString",
    "method"
  ],
  [
    "lib/spray.js~spray#updatestate",
    "class/lib/spray.js~Spray.html#instance-method-updateState",
    "lib/spray.js~Spray#updateState",
    "method"
  ],
  [
    "lib/spray.js~spray#verbose",
    "class/lib/spray.js~Spray.html#instance-member-verbose",
    "lib/spray.js~Spray#verbose",
    "member"
  ]
]